# WirePlumber 0.5 libcamera monitor rules for the four SM-X910 cameras.
monitor.libcamera.rules = [
  {
    matches = [ { node.name = "libcamera_input._base_soc_0_geniqup_8c0000_i2c_884000_camera_21" } ]
    actions = { update-props = { media.class = "Video/Source" node.description = "GTS9U Front Ultra-Wide" } }
  }
  {
    matches = [ { node.name = "libcamera_input._base_soc_0_cci_ac16000_i2c-bus_1_camera_20" } ]
    actions = { update-props = { media.class = "Video/Source" node.description = "GTS9U Front Main" } }
  }
  {
    matches = [ { node.name = "libcamera_input._base_soc_0_cci_ac15000_i2c-bus_1_camera_21" } ]
    actions = { update-props = { media.class = "Video/Source" node.description = "GTS9U Rear Main" } }
  }
  {
    matches = [ { node.name = "libcamera_input._base_soc_0_cci_ac15000_i2c-bus_0_camera_21" } ]
    actions = { update-props = { media.class = "Video/Source" node.description = "GTS9U Rear Ultra-Wide" } }
  }
]
